apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-chart.fullname" . }}
  labels:
    app: {{ include "backend-chart.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "backend-chart.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.targetPort }}
